version: '3.4'

volumes:
  zookeeper-data:
  kafka-single-data:

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - '2181:2181'
    environment:
      - ZOO_MY_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper
  
  kafka-single:
    image: bitnami/kafka:3.2
    container_name: kafka-single
    expose:
      - '29092'
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://kafka-single:29092,EXTERNAL://kafka-single:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-single:29092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    volumes:
      - kafka-single-data:/bitnami/kafka
    depends_on:
      - zookeeper

  jobmanager:
    platform: linux/x86_64
    image: flink:1.13.2-scala_2.12
    #container_name: flink-jobmanager
    ports:
      - '8081:8081'
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager  
        rest.flamegraph.enabled: true
    profiles:
      - flink-cluster

  taskmanager:
    platform: linux/x86_64
    image: flink:1.13.2-scala_2.12
    #container_name: flink-taskmanager
    command: taskmanager
    scale: 4
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        rest.flamegraph.enabled: true
    depends_on:
      - jobmanager
    profiles:
      - flink-cluster